# cspell:word clippy
# cspell:word hadolint
# cspell:word markdownlint
# cspell:word mdformat
# cspell:word shfmt
---
repos:
-
  hooks:
  -
    # Lint all AWS CloudFormation files ending in `.cfn.yaml`.
    files: '.*\.cfn\.yaml'
    id: 'cfn-lint'
  repo: 'https://github.com/aws-cloudformation/cfn-lint'
  rev: 'v1.8.2'
-
  hooks:
  -
    args:
    - '--config-file'
    - 'cfg/yamllint-config.yaml'
    - '--strict'
    id: 'yamllint'
  repo: 'https://github.com/adrienverge/yamllint'
  rev: 'v1.34.0'
-
  hooks:
  -
    entry: './src/sh/ensure-shebang.sh'
    id: 'ensure-shebang'
    language: 'script'
    name: 'Ensure shebang'
  repo: 'local'
-
  hooks:
  - id: 'check-added-large-files'
  - id: 'check-case-conflict'
  - id: 'detect-private-key'
  - id: 'end-of-file-fixer'
  -
    files: 'cfg/cspell-dictionary.txt'
    id: 'file-contents-sorter'
  - id: 'mixed-line-ending'
  -
    args:
    - '--autofix'
    id: 'pretty-format-json'
  - id: 'trailing-whitespace'
  repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: 'v4.5.0'
-
  hooks:
  - additional_dependencies:
    - 'mdformat-gfm'
    id: 'mdformat'
  repo: 'https://github.com/executablebooks/mdformat'
  rev: '0.7.17'
-
  hooks:
  -
    args:
    - '--config'
    - 'cfg/markdownlint-config.yaml'
    id: 'markdownlint-fix'
  repo: 'https://github.com/igorshubovych/markdownlint-cli'
  rev: 'v0.39.0'
-
  hooks:
  - id: 'hadolint-docker'
  repo: 'https://github.com/hadolint/hadolint'
  rev: 'v2.12.0'
-
  hooks:
  -
    args:
    - '--config-file'
    - 'cfg/yamllint-config.yaml'
    - '--strict'
    id: 'yamllint'
  repo: 'https://github.com/adrienverge/yamllint'
  rev: 'v1.34.0'
-
  hooks:
  - id: 'shfmt'
  repo: 'https://github.com/scop/pre-commit-shfmt'
  rev: 'v3.7.0-4'
-
  hooks:
  -
    args:
    - '--config'
    - 'cfg/cspell-config.json'
    id: 'cspell'
  repo: 'https://github.com/streetsidesoftware/cspell-cli'
  rev: 'v8.3.0'
-
  hooks:
  -
    args:
    - '--autofix'
    exclude: 'Cargo.lock'
    id: 'pretty-format-toml'
  repo: 'https://github.com/macisamuele/language-formatters-pre-commit-hooks'
  rev: 'v2.12.0'
-
  hooks:
  -
    args:
    - '--all'
    - '--manifest-path'
    - 'src/Cargo.toml'
    - '--'
    id: 'fmt'
  -
    args:
    - '--manifest-path'
    - 'src/Cargo.toml'
    - '--'
    id: 'cargo-check'
  -
    args:
    - '--manifest-path'
    - 'src/Cargo.toml'
    - '--'
    id: 'clippy'
  repo: 'https://github.com/doublify/pre-commit-rust'
  rev: 'v1.0'
...
