---
services:
  redis:
    image: 'redis:7.4.0-alpine3.20'
  server:
    build:
      args:
        BIN: 'allowlist'
        BUILDER_VERSION: '1.0.0'
        PACKAGE: 'allowlist'
      context: '../'
      dockerfile: 'rust-builder/template.Dockerfile'
    depends_on:
    - 'redis'
    environment:
      REDIS_URL: 'redis://redis:6379'
      SERVER_URL: '0.0.0.0:3000'
    image: 'econialabs/allowlist:latest'
    links:
    - 'redis'
    ports:
    - '3000:3000'
    pull_policy: 'missing'
    restart: 'unless-stopped'
...
