# Build and push allowlist Docker image to Docker Hub whenever a tag of the
# pattern allowlist-v* is pushed.
---
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/allowlist'
        tags: |
          type=match,pattern=allowlist-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        build-args: |
          BIN=allowlist
          BUILDER_VERSION=0.1.0
          PACKAGE=allowlist
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: 'src'
        file: 'src/rust-builder/template.Dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        platforms: '${{ vars.DOCKER_IMAGE_PLATFORMS }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
name: 'Build allowlist Docker image and push to Docker Hub'
'on':
  push:
    tags:
    - 'allowlist-v*'
...
